version: '2'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "AprendaMais"
    volumes:
      - ./sql:/var/lib/mysql
    networks:
      - rede-qa
  go:
    image: golang
    networks:
      - rede-qa
    depends_on:
      - "mysql"
    volumes:
      - ./src:/usr/local/go/src

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - rede-qa
    depends_on:
      - "mysql"

networks:
  rede-qa:
    driver: bridge