version: '3.1'

services:
  mysql:
    build:
      context: ./sql
      dockerfile: ./Dockerfile
      target: aprendaDb
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "AprendaMais"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - dev
  app:
    build:
      context: ./src
      dockerfile: ./Dockerfile
      target: aprendaApp
    export:
      - "5000:5000"
    networks:
      - dev
    depends_on:
      - mysql
    volumes:
      - aprendamais:/go/src/aprendamais

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      target: aprendaFront
    export:
      - "3000:3000"
    networks:
      - dev
    depends_on:
      - mysql
      - app

networks:
  dev: