version: '3.1'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "AprendaMais"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - dev
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: aprendaApp
    ports:
      - "5000:5000"
    networks:
      - dev
    depends_on:
      - mysql
    volumes:
      - aprendamais:/go/src/aprendamais

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: aprendaFront
    ports:
      - "3000:3000"
    networks:
      - dev
    depends_on:
      - mysql
      - app

volumes:
  aprendamais:

networks:
  dev: